"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import {AppIcon} from "../components/app-icon";
import {mesApi} from "./mes-live-api";

type Product={id:string;code:string;name:string;unitCode:string;resolutionStatus:string;version:number;resolvedBy:string|null;resolvedAt:string|null;updatedAt:string};
type Partner={id:string;type:string;key:string;code:string|null;name:string|null;resolutionStatus:string;version:number;resolvedBy:string|null;resolvedAt:string|null;updatedAt:string};
type Page<T>={items:T[];total:number};
type Tab="products"|"partners"|"warehouses"|"indicators"|"vehicles";
const tabs:[Tab,string][]=[["products","Sản phẩm"],["partners","Đối tác"],["warehouses","Kho/Cảng"],["indicators","Chỉ tiêu"],["vehicles","Phương tiện"]];

export default function MesMasterData({apiUrl}:{apiUrl:string}){
 const[tab,setTab]=useState<Tab>("products");const[products,setProducts]=useState<Product[]>([]);const[partners,setPartners]=useState<Partner[]>([]);const[total,setTotal]=useState(0);const[search,setSearch]=useState("");const[status,setStatus]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[selected,setSelected]=useState<Product|Partner>();
 const live=tab==="products"||tab==="partners";
 const load=useCallback(async()=>{if(!live)return;setLoading(true);setError("");try{const path=tab==="products"?"products":"partners";const data=await mesApi<Page<Product|Partner>>(apiUrl,`/api/v1/mes/master-data/${path}?status=${status}&search=${encodeURIComponent(search)}&size=100`);setTotal(data.total);if(tab==="products")setProducts(data.items as Product[]);else setPartners(data.items as Partner[]);}catch(c){setError(c instanceof Error?c.message:"Không tải được master data.");}finally{setLoading(false);}},[apiUrl,live,search,status,tab]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),200);return()=>window.clearTimeout(timer);},[load]);
 const saved=()=>{setSelected(undefined);setNotice("Master data đã được cập nhật và ghi audit.");void load();};
 return <div className="mes-workspace mes-live-workspace"><div className="page-heading mes-page-heading"><div><p className="eyebrow">MES Than Mạo Khê · Data Governance</p><h1>Danh mục & ánh xạ dữ liệu</h1><p className="page-description">Xác nhận các chiều canonical và quản lý ánh xạ trước khi dùng cho đối soát, báo cáo và Dashboard điều hành.</p></div><div className="mes-heading-actions"><button className="secondary-button" disabled={loading||!live} onClick={()=>void load()}><AppIcon name="refresh" size={14}/>{loading?"Đang tải":"Làm mới"}</button></div></div>
 {error&&<p className="operation-message error" role="alert">{error}</p>}{notice&&<p className="operation-message" role="status">{notice}</p>}
 <div className="mes-tabs">{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>{setTab(key);setSearch("");setStatus("");setNotice("");}}>{label}</button>)}</div>
 {live?<><section className="panel mes-master-toolbar"><label><AppIcon name="search" size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm mã hoặc tên..."/></label><select aria-label="Trạng thái xác nhận" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option><option value="UNVERIFIED">Chưa xác nhận</option><option value="RESOLVED">Đã xác nhận</option></select><span>{total} bản ghi</span></section>
 <section className="panel table-panel mes-table-panel"><div className="mes-table-scroll"><table><thead><tr><th>STT</th><th>Loại</th><th>Mã</th><th>Tên chuẩn</th>{tab==="products"&&<th>ĐVT</th>}<th>Trạng thái</th><th>Người xác nhận</th><th>Phiên bản</th><th>Thao tác</th></tr></thead><tbody>{(tab==="products"?products:partners).map((item,index)=>{const product=tab==="products"?item as Product:null;const partner=tab==="partners"?item as Partner:null;return <tr key={item.id}><td>{index+1}</td><td>{product?"Sản phẩm":partner?.type==="SUPPLIER"?"Nhà cung cấp":"Khách hàng"}</td><td><strong>{product?.code||partner?.code||"—"}</strong></td><td>{product?.name||partner?.name||"—"}</td>{product&&<td>{product.unitCode}</td>}<td><span className={`mes-status ${item.resolutionStatus==="RESOLVED"?"green":"amber"}`}>{item.resolutionStatus==="RESOLVED"?"Đã xác nhận":"Chưa xác nhận"}</span></td><td>{item.resolvedBy||"—"}</td><td>{item.version}</td><td><button className="mes-icon-button" title="Xem và xác nhận" onClick={()=>setSelected(item)}><AppIcon name="eye" size={15}/></button></td></tr>})}{!loading&&(tab==="products"?products:partners).length===0&&<tr><td className="mes-empty" colSpan={tab==="products"?9:8}>Chưa có master data. Dữ liệu được tạo khi lô báo cáo hợp lệ được khóa.</td></tr>}</tbody></table></div></section></>:<section className="panel mes-canonical-empty"><AppIcon name="database" size={26}/><div><h2>Chưa có Data Contract cho {tabs.find(([key])=>key===tab)?.[1]}</h2><p>Danh mục này chưa xuất hiện trong 6 workbook pilot. Hệ thống không tạo dữ liệu mô phỏng hoặc tự suy diễn master.</p></div></section>}
 {selected&&<MasterModal apiUrl={apiUrl} item={selected} kind={tab==="products"?"product":"partner"} onClose={()=>setSelected(undefined)} onSaved={saved}/>}</div>;
}

function MasterModal({apiUrl,item,kind,onClose,onSaved}:{apiUrl:string;item:Product|Partner;kind:"product"|"partner";onClose:()=>void;onSaved:()=>void}){
 const product=kind==="product"?item as Product:null;const partner=kind==="partner"?item as Partner:null;const[code,setCode]=useState(product?.code||partner?.code||"");const[name,setName]=useState(product?.name||partner?.name||"");const[unit,setUnit]=useState(product?.unitCode||"TONNE");const[status,setStatus]=useState(item.resolutionStatus);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{const path=kind==="product"?`products/${item.id}`:`partners/${item.id}`;await mesApi(apiUrl,`/api/v1/mes/master-data/${path}`,{method:"PATCH",body:JSON.stringify(kind==="product"?{code,name,unitCode:unit,resolutionStatus:status,expectedVersion:item.version}:{code,name,resolutionStatus:status,expectedVersion:item.version})});onSaved();}catch(c){setError(c instanceof Error?c.message:"Không thể cập nhật master data.");}finally{setBusy(false);}};
 return <div className="modal-backdrop" onMouseDown={onClose}><section className="panel mes-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header><div><p className="eyebrow">Data Steward · Phiên bản {item.version}</p><h2>Xác nhận {kind==="product"?"sản phẩm":"đối tác"}</h2></div><button onClick={onClose} aria-label="Đóng"><AppIcon name="x" size={16}/></button></header><form className="mes-form" onSubmit={submit}><label>Mã chuẩn<input required={kind==="product"} maxLength={100} value={code} onChange={e=>setCode(e.target.value)}/></label><label>Tên chuẩn<input required maxLength={240} value={name} onChange={e=>setName(e.target.value)}/></label>{product&&<label>Đơn vị chuẩn<input required maxLength={40} value={unit} onChange={e=>setUnit(e.target.value.toUpperCase())}/></label>}<label>Trạng thái<select value={status} onChange={e=>setStatus(e.target.value)}><option value="UNVERIFIED">Chưa xác nhận</option><option value="RESOLVED">Đã xác nhận</option></select></label><div className="mes-form-note wide"><AppIcon name="shield" size={15}/><span>Thao tác được kiểm soát bằng quyền MES_MASTER_DATA:APPROVE, chống ghi đè theo phiên bản và ghi audit.</span></div>{error&&<p className="operation-message error wide" role="alert">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>Đóng</button><button className="primary-button" disabled={busy}>{busy?"Đang lưu":"Xác nhận"}</button></footer></form></section></div>;
}
