"use client";

import {useCallback,useEffect,useState} from "react";
import {AppIcon} from "../components/app-icon";
import {mesApi,viNumber} from "./mes-live-api";

type Item={productId:string;productCode:string;productName:string;unitCode:string;masterDataStatus:string;openingStock:number|null;receipts:number;issues:number;expectedClosingStock:number|null;reportedClosingStock:number|null;variance:number|null;status:string;reason:string};
type Result={reportingDate:string;openingDate:string;coveredContracts:number;requiredContracts:number;coverageComplete:boolean;totalProducts:number;balanced:number;variances:number;incomplete:number;unverifiedMasterData:number;items:Item[]};
const today=()=>new Date().toLocaleDateString("en-CA");
const labels:Record<string,string>={BALANCED:"Cân bằng",VARIANCE:"Chênh lệch",INCOMPLETE:"Thiếu dữ liệu",MASTER_UNVERIFIED:"Chưa xác nhận master"};

export default function MesInventoryReconciliation({apiUrl}:{apiUrl:string}){
 const[date,setDate]=useState(today);const[data,setData]=useState<Result>();const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await mesApi<Result>(apiUrl,`/api/v1/mes/reconciliation/inventory?date=${date}&size=100`));}catch(c){setError(c instanceof Error?c.message:"Không tải được dữ liệu đối soát.");}finally{setLoading(false);}},[apiUrl,date]);
 useEffect(()=>{void load();},[load]);
 return <div className="mes-workspace mes-live-workspace"><div className="page-heading mes-page-heading"><div><p className="eyebrow">MES Than Mạo Khê · Dữ liệu canonical</p><h1>Kho & dòng than</h1><p className="page-description">Đối soát nhập – xuất – tồn theo facts canonical; kỳ trước là ngày liền trước ngày báo cáo.</p></div><div className="mes-heading-actions"><label className="mes-date-control">Ngày đối soát<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="secondary-button" disabled={loading} onClick={()=>void load()}><AppIcon name="refresh" size={14}/>{loading?"Đang tải":"Làm mới"}</button></div></div>{error&&<p className="operation-message error" role="alert">{error}</p>}
 <section className="mes-report-summary"><Summary label="Độ phủ dữ liệu" value={`${data?.coveredContracts||0}/${data?.requiredContracts||5}`} tone={data?.coverageComplete?"green":"amber"}/><Summary label="Cân bằng" value={String(data?.balanced||0)} tone="green"/><Summary label="Chênh lệch" value={String(data?.variances||0)} tone={(data?.variances||0)>0?"red":"green"}/><Summary label="Thiếu dữ liệu" value={String((data?.incomplete||0)+(data?.unverifiedMasterData||0))} tone={(data?.incomplete||data?.unverifiedMasterData||0)>0?"amber":"green"}/></section>
 <section className="panel mes-reconciliation-rule"><AppIcon name="chart-combined" size={20}/><div><strong>Quy tắc kiểm soát</strong><p>Tồn cuối {data?.openingDate||"ngày trước"} + Nhập {date} − Xuất {date} = Tồn cuối báo cáo {date}. Không áp dụng ngưỡng sai số ngầm định.</p></div></section>
 <section className="panel table-panel mes-table-panel"><div className="mes-table-scroll"><table><thead><tr><th>STT</th><th>Mã / sản phẩm</th><th>Tồn đầu</th><th>Nhập</th><th>Xuất</th><th>Tồn tính toán</th><th>Tồn báo cáo</th><th>Chênh lệch</th><th>Kết quả</th><th>Lý do</th></tr></thead><tbody>{(data?.items||[]).map((item,index)=><tr key={item.productId}><td>{index+1}</td><td><strong>{item.productCode}</strong><small>{item.productName}</small></td><td className="numeric">{viNumber(item.openingStock)}</td><td className="numeric">{viNumber(item.receipts)}</td><td className="numeric">{viNumber(item.issues)}</td><td className="numeric">{viNumber(item.expectedClosingStock)}</td><td className="numeric">{viNumber(item.reportedClosingStock)}</td><td className="numeric">{viNumber(item.variance)}</td><td><span className={`mes-status ${item.status==="BALANCED"?"green":item.status==="VARIANCE"?"red":"amber"}`}>{labels[item.status]||item.status}</span></td><td>{item.reason}</td></tr>)}{!loading&&!data?.items.length&&<tr><td colSpan={10} className="mes-empty">Chưa có dữ liệu canonical cho ngày đã chọn.</td></tr>}</tbody></table></div><footer className="mes-table-footer"><span>{data?.totalProducts||0} sản phẩm trong phạm vi đối soát</span></footer></section></div>;
}
function Summary({label,value,tone}:{label:string;value:string;tone:string}){return <article className="panel"><span className={`mes-kpi-icon ${tone}`}><AppIcon name="warehouse" size={17}/></span><div><small>{label}</small><strong>{value}</strong></div></article>}
